### ISSUE TITLE
BUG: User can only tab and select the first asset (Bitcoin) but cannot tab again to select other assets.

### ISSUE THREAD

**Issue by leongaban** [Futuratum/moon.holdings#112]
https://stackoverflow.com/questions/52998354/why-does-tabindex-not-work-after-first-tab-to-select-li

![list](https://user-images.githubusercontent.com/191636/47531392-2649a780-d873-11e8-9849-f45e1900614a.jpg)

![screen shot 2018-10-25 at 4 24 31 pm](https://user-images.githubusercontent.com/191636/47531409-306ba600-d873-11e8-9e7c-d7d0c4d920c5.png)

    <ul id="coins-list">
      { assets !== 'undefined'
        ? assets.map((asset, i) => (
          <li
            key={asset.currency}
            role="button"
            tabIndex={i}
            onFocus={() => this.setFocus(asset)}
            onBlur={this.onBlur}
            onClick={() => this.handleSelect(asset)}
          >
            {asset.name}
            <span className="symbol">{asset.currency}</span>
          </li>))
        : <li>Loading...</li>
      }
    </ul>

**Comment by Swivelgames** [comment]
The problem isn't your use of `tabindex` (although, it isn't the most recommended thing in the world). The problem is that you've got both an `onFocus` and `onBlur` that are doing conflicting things:

**[/app/containers/SearchModal/searchModal.js](https://github.com/Futuratum/moon.holdings/blob/92fc539815a898b3bc53b1f37aa64993e9823b08/app/containers/SearchModal/searchModal.js#L43-L50)**
```javascript
  onBlur() {
    this.setState({ focused: {} });
  }

  setFocus(coin) {
    console.log('setFocus coin:', coin);
    this.setState({ focused: coin });
  }
```

Right now they're fighting over each other.

A cursory solution might be to use an `onfocusout` on your `ul` element instead of an `onBlur` on your `li` elements? That way you don't set `focused` to `{}` just because you changed one tab to the next.

If that doesn't work, there may be some other solutions you might be able to implement.

**Comment by leongaban** [comment]
Thanks @Swivelgames I tried using the `onFocusOut` on the `ul` but that didn't change how it currently acts.

From this answer here, the guy is suggesting that we not use tabindex, which doesn't entirely make sense to me, but I guess next steps would be to try using the arrow keys.

https://stackoverflow.com/questions/52998354/why-does-tabindex-not-work-after-first-tab-to-select-li

**Comment by leongaban** [comment]
Closing this issue as the new Search will be redesigned in Version 2.
